### PR TITLE
Add Onboarding Notes to the Styleguide README.rst

### PR DESCRIPTION
**Pull request by hcs0**
Scope
=====

During the Onboarding stage, the Styleguide is a good starting point to contribute to the Chevah project.

Why we got into this (5 whys)
=============================

We want to encourage new Onboarding members to use the Styleguide repository as a starting point.

The Styleguide is an internal resource (so it's not customer facing) and it doesn't involve buildbot (which may be used by development team doing server work).

Changes
=======

Add Onboarding steps to the Styleguide Readme.rst.

How to try and test the changes
===============================

reviewers: @AndradaE 

You will notice the email reply is also used here.

Please take a look and see if the steps is a guide to creating a new PR with your changes.

Once this is confirmed, please do a "changes-approved" comment otherwise send through additional q's.

### CODE REVIEW

**Comment by adiroiban** [comment]
this looks good, but maybe we can make it as a full page... and in the future add more info to publicly describe our onboarding process... that is, it should not be just a footnote in the README.rst :)

thanks!

**Comment by hcs0** [comment]
Ticket created - 3967

**Comment by AndradaE** [comment]
If it helps, these are the steps I had to go through to set up the files locally to be able to make changes:
> 1. Go to the repo on GitHub https://github.com/chevah
> 2. Get link from “GitHub Clone Download” button
> 3. Navigate to a folder (i.e Work)
> 4. Run git clone (paste link from GitHub)
> 5. Go to newly created folder (i.e syleguide)
> 6. Run git checkout -b 1234-new-branch-name. The 1234 stands for the Trac ticket associated with the changes.
> 7. Run ./paver.sh run
> 8. Go to http://localhost:8080
> 9. Open folder (Work/syleguide) in text editor

The actual shell commands can be formatted in a smaller font like you usually do to set them apart. Since they have to be executed in this order it helps the reader to place them in an ordered list. The same goes for the steps needed to make commits and push the files/changes.

And at the end you could also add the instruction on doing a pull request:

> Once all changes are made you can push your changes out to your git branch (not the Master branch) and create the first Pull Request. To create the pull request go to the branch’s page on github.com and click on "Compare and Pull Request" button.

**Comment by hcs0** [comment]
@AndradaE 

Thanks for the feedback.  I rewrote it so that it is more of a guide that someone can take and they don't need to strictly follow it. 

The development notes like ``paver deps`` are already mentioned

The shell commands are in the form of `` so you will know that they are shell.

Please comment ``changes-approved``and I will squash and merge this.

--------

After the squash and merge, the main Styleguide repository will have changed.

If you have already created a git branch locally, you will need to also do:

`` git pull origin master ``

In your own branch.  This ensures to update the master branch in your own branch.

You will find that when you start contributing on more busier repos like ``server``, since there are constant changes it's good to see how this works in a quiet repo like ``styleguide``.

--------

It would be a good idea to look at the Github how to guides as well.  The Chevah Styleguide does have steps on the process (like git) specifically for the Chevah project, but it's always good to check out the official documentation (ie for Github) available.

**Comment by hcs0** [comment]
> I understand why you wanted to put this info in the README but I agree with Adi that this should be a dedicated page in the Style Guide (a page for Onboarding maybe).

I created a new ticket for it for near future work, but will wait to get your feedback on the Onboarding as there may be more that we need to add...

> I'm not sure I understand how I'd generate a new page.

The Styleguide uses the RST system which is the same system used for the website and styleguide.  
To update the documentation like create a new page, see http://styleguide.chevah.com/documentation.html#updating-the-documentation (under **Tips when updating documentation:**).

But if there is anything missing about updating the documentation we can add this here as this would apply not just for the Styleguide.

> When would I run "paver dev"? Each time I turn on the server? Should "paver publish" be here considering the detailed info about publishing below Onboarding Notes?

You can run ``paver deps`` ``paver run`` before you make a change (to run the Styleguide locally first) or you can run this after making the changes (to see your changes).  However...you definitely need to run these two commands after making a change so that you can see your changes locally.
In this case, I added a line to check the Development notes (that's also in the same page) after all the git steps.  

Just a note that the changes I added - https://github.com/chevah/styleguide/pull/48/files - are only the additions that I am adding to the README.rst.  Github only shows the **diff** or the additions.  But you can view the rest of the file by clicking on the 'Expand' icon on the top left

**Comment by AndradaE** [comment]
OK. Thanks for the info Hannah!

changes-approved

**Comment by hcs0** [comment]
@AndradaE Thanks, this is squashed and merged now to the main master branch now.

**Pull request merged**
