### PR TITLE
Add Mailchimp steps to Release page

### PR DESCRIPTION
**Pull request by hcs0**
Scope
=====
Discussions at https://github.com/chevah/styleguide/issues/34

Changes
=======
Steps added end of the page since newsletter should be the last item done in a Release process.

How to try and test the changes
========================
reviewers: @adiroiban

### CODE REVIEW

**Comment by adiroiban** [comment]
Thanks for this. We will do a new release soon, and I will validate this PR as part of that release.

Thanks!

**Comment by hcs0** [comment]
@alibotean can this be merged?
There is no Trac tags or ID in this as the PR was created during the onboarding / before I had Trac access.

**Comment by alibotean** [comment]
Sure, sorry. I missed this completely.

**Comment by alibotean** [comment]
> and I will validate this PR as part of that release.

Looks like there is some validation needed/required by @adiroiban first though.

**Comment by hcs0** [comment]
Sorry from me actually - it should be @adiroiban not you @alibotean !
Thanks

**Comment by adiroiban** [comment]
Let me try to follow the process for release 3.13.2 and then we can close this.

Thanks!

sorry for taking so long to close this

**Comment by adiroiban** [comment]
Thanks, I have sent the news for 3.13.2 

Mailchimp has a strange UI.

With you current guide there are no hints about what content to use for the email and how to review it.

Maybe it should be exlicit the the message should be the same as the one used for the news article.

changes-approved

**Pull request merged**
